name: Node CI

on: [push, pull_request]

jobs:
  test:
    name: Test on Node.js ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: npm install
      run: npm ci

    - name: typescript build
      run: npm run build

    - name: lint
      run: npm run lint

    - name: test
      run: npm test
